rmdir /S /Q beam-aatsr-sst
rmdir /S /Q beam-atsr-reader
rmdir /S /Q beam-avhrr-reader
rmdir /S /Q beam-binning
rmdir /S /Q beam-bootstrap
rmdir /S /Q beam-chris-reader
rmdir /S /Q beam-flhmci
rmdir /S /Q beam-help
rmdir /S /Q beam-installer
rmdir /S /Q beam-meris-cloud
rmdir /S /Q beam-meris-ndvi
rmdir /S /Q beam-meris-radtorefl
rmdir /S /Q beam-meris-smac
rmdir /S /Q beam-meris-smile
rmdir /S /Q beam-merisl3-reader
rmdir /S /Q beam-obpg-reader
rmdir /S /Q beam-pconvert
rmdir /S /Q beam-rtp-codec
rmdir /S /Q beam-unmix
