package org.esa.snap.remote.execution.exceptions;

/**
 * Created by jcoravu on 23/5/2019.
 */
public enum ExecutionExceptionType {
    NO_REMOTE_MACHINE_AVAILABLE,
    NO_REMOTE_MACHINE_MOUNT_SHARED_FOLDER,
    UNPROCESSED_MASTER_OUTPUT_PRODUCT,
    UNPROCESSED_SLAVE_OUTPUT_PRODUCTS,
    UNPROCESSED_SOURCE_PRODUCTS,
    FAILED_TO_DELETE_OUTPUT_SLAVE_PRODUCTS_FOLDER,
    FAILED_TO_CREATE_OUTPUT_SLAVE_PRODUCTS_FOLDER
}
