/*
 * Copyright (C) 2010 Brockmann Consult GmbH (info@brockmann-consult.de)
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option)
 * any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, see http://www.gnu.org/licenses/
 */

package org.esa.beam.processor.radtorefl;

import org.esa.beam.dataio.envisat.EnvisatConstants;
import org.esa.beam.framework.processor.ProcessorConstants;


public class RadToReflConstants implements ProcessorConstants {
	public static final String PROCESSOR_NAME = "BEAM Radiance-To-Reflectance Processor";
    public static final String PROCESSOR_SYMBOLIC_NAME = "beam-meris-radtorefl";
	public static final String VERSION = "1.3.301";
	public static final String COPYRIGHT = "Copyright (C) 2006 Brockmann Consult (info@brockmann-consult.de)";

    public static final String REQUEST_TYPE = "RAD_TO_REFL";

	public static final String INPUT_BANDS_PARAM_NAME = "bands";
    public static final String[] INPUT_BANDS_PARAM_DEFAULT = EnvisatConstants.MERIS_L1B_SPECTRAL_BAND_NAMES;
    public static final String INPUT_BANDS_PARAM_LABEL = "Bands";
    
    public static final String COPY_INPUT_BANDS_PARAM_NAME = "copy_bands";
    public static final Boolean COPY_INPUT_BANDS_PARAM_DEFAULT = Boolean.FALSE;
    public static final String COPY_INPUT_BANDS_PARAM_LABEL = "Copy selected bands to output product";
    
    public static final String DEFAULT_LOG_PREFIX = "radtorefl";
    public static final Boolean DEFAULT_LOG_TO_OUTPUT = Boolean.FALSE;
    public static final String DEFAULT_OUTPUT_PRODUCT_FILE_NAME = "reflectances.dim";

    public static final String LOGGER_NAME = "beam.processor.radtorefl";
    public static final String LOG_MSG_HEADER = "Logfile generated by " + PROCESSOR_NAME + ", version " + VERSION;
    public static final String LOG_MSG_LOAD_SZA_START = "Loading sun zenith tie point grid...";
    public static final String LOG_MSG_LOAD_SZA_END = "Loaded sun zenith tie point grid";
    public static final String LOG_MSG_PROC_START = "Converting radiances to reflectances...";
    public static final String LOG_MSG_PROC_BAND_1 = "Processing band '";
    public static final String LOG_MSG_PROC_BAND_2 = "'...";
    public static final String LOG_MSG_UNSUPPORTED_PRODUCT = "The requested input product is not supported. Currently, only MERIS Level 1b products are supported.";
}

